services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
    restart: always
    pull_policy: always # ⬅️ Ensures it always pulls the latest image
    ports:
      - 3001:3001
    volumes:
      - ./data:/usr/src/app/data
